package forms;
import static forms.Database.*;
import static javax.swing.JOptionPane.*;


public class company extends javax.swing.JFrame {
    private static String input = "";
    /**
     * Creates new form Company
     */
    public company() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cbxBillPeriod = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBaseResidential = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBaseGS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtBaseGP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        txtRAdd4 = new javax.swing.JTextField();
        txtRAdd1 = new javax.swing.JTextField();
        txtRAdd2 = new javax.swing.JTextField();
        txtRAdd3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtRDisc1 = new javax.swing.JTextField();
        txtRDisc2 = new javax.swing.JTextField();
        txtRDisc3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtGSAdd4 = new javax.swing.JTextField();
        txtGSAdd1 = new javax.swing.JTextField();
        txtGSAdd2 = new javax.swing.JTextField();
        txtGSAdd3 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        txtRService = new javax.swing.JTextField();
        txtRDisc4 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        txtGPAdd1 = new javax.swing.JTextField();
        txtGPAdd2 = new javax.swing.JTextField();
        txtGPAdd3 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(242, 100, 25));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(60, 63, 66));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HELIOS SYSTEMS INC.   RATES");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 730, 60));

        jPanel5.setBackground(new java.awt.Color(242, 100, 25));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 10, 60));

        cbxBillPeriod.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbxBillPeriod.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbxBillPeriod.setPreferredSize(new java.awt.Dimension(90, 22));
        cbxBillPeriod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxBillPeriodItemStateChanged(evt);
            }
        });
        cbxBillPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBillPeriodActionPerformed(evt);
            }
        });
        jPanel2.add(cbxBillPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 110, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Billing Period:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 90, 20));

        btnLogOut.setBackground(new java.awt.Color(242, 100, 25));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 40, 100, 30));

        btnSave.setBackground(new java.awt.Color(242, 100, 25));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(null);
        btnSave.setBorderPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 100, 30));

        btnNew.setBackground(new java.awt.Color(242, 100, 25));
        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setText("New");
        btnNew.setBorder(null);
        btnNew.setBorderPainted(false);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel2.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 100));

        jPanel3.setBackground(new java.awt.Color(242, 100, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1280, 10));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("GENERAL POWER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, 200, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel3.setText("Additional Charges");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 210, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setText("GENERAL SERVICE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 140, 210, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 130, 4, 530));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 130, 4, 530));

        jLabel5.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel5.setText("per kWh");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel6.setText("(per kWh)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 60, 20));

        txtBaseResidential.setBackground(new java.awt.Color(235, 235, 235));
        txtBaseResidential.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtBaseResidential.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBaseResidential.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtBaseResidential.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtBaseResidential, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 105, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel7.setText("per kWh");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("Base Rate:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));

        txtBaseGS.setBackground(new java.awt.Color(235, 235, 235));
        txtBaseGS.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtBaseGS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBaseGS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtBaseGS.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtBaseGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 105, 30));

        jLabel9.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel9.setText("per kWh");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, 30));

        jTextField4.setBackground(new java.awt.Color(235, 235, 235));
        jTextField4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField4.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 105, 30));

        jLabel11.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel11.setText("per kWh");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, 30));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setText("Base Rate:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, 30));

        txtBaseGP.setBackground(new java.awt.Color(235, 235, 235));
        txtBaseGP.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtBaseGP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBaseGP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtBaseGP.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtBaseGP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, 105, 30));

        jLabel13.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel13.setText("per kWh");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 180, -1, 30));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel14.setText("Base Rate:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, -1, 30));

        jTextField6.setBackground(new java.awt.Color(235, 235, 235));
        jTextField6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField6.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, 105, 30));

        jLabel15.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel15.setText("per kWh");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 180, -1, 30));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setText("Base Rate:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, -1, 30));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel17.setText("RESIDENTIAL");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 140, 150, 30));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel18.setText("Base Rate:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));

        jLabel19.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel19.setText("Adt'l Charge");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 100, 20));

        jTextField7.setBackground(new java.awt.Color(235, 235, 235));
        jTextField7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField7.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 105, 30));

        txtRAdd4.setBackground(new java.awt.Color(235, 235, 235));
        txtRAdd4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRAdd4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRAdd4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtRAdd4.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtRAdd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 80, -1));

        txtRAdd1.setBackground(new java.awt.Color(235, 235, 235));
        txtRAdd1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRAdd1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRAdd1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtRAdd1.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtRAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 80, -1));

        txtRAdd2.setBackground(new java.awt.Color(235, 235, 235));
        txtRAdd2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRAdd2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRAdd2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtRAdd2.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtRAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 80, -1));

        txtRAdd3.setBackground(new java.awt.Color(235, 235, 235));
        txtRAdd3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRAdd3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRAdd3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtRAdd3.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtRAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 80, -1));

        jLabel27.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel27.setText("(kWh)");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 40, 20));

        jLabel21.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel21.setText("Consumption");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 110, 20));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setText("-");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 300, 10, 24));

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel37.setText("200");
        jLabel37.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, 24));

        jLabel38.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel38.setText("0");
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, 24));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setText("-");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 330, 10, 24));

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel39.setText("300");
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, 24));

        jLabel40.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel40.setText("201");
        jLabel40.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 24));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setText("-");
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 360, 10, 24));

        jLabel41.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel41.setText("400");
        jLabel41.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, 24));

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel42.setText("301");
        jLabel42.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, 24));

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel44.setText("400+");
        jLabel44.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, 24));

        jLabel30.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel30.setText("Service Charges");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 210, 24));

        jLabel31.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel31.setText("      (%)");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 60, 20));

        jLabel32.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel32.setText("Discounted by");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 120, 20));

        txtRDisc1.setBackground(new java.awt.Color(235, 235, 235));
        txtRDisc1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRDisc1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRDisc1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtRDisc1.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtRDisc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 80, -1));

        txtRDisc2.setBackground(new java.awt.Color(235, 235, 235));
        txtRDisc2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRDisc2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRDisc2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtRDisc2.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtRDisc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 80, -1));

        txtRDisc3.setBackground(new java.awt.Color(235, 235, 235));
        txtRDisc3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRDisc3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRDisc3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtRDisc3.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtRDisc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 80, -1));

        jLabel33.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel33.setText("(kWh)");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 40, 20));

        jLabel34.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel34.setText("Consumption");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 110, 20));

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel35.setText("-");
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 500, 10, 24));

        jLabel43.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel43.setText("20");
        jLabel43.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, 24));

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel45.setText("0");
        jLabel45.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, 24));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel36.setText("-");
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 530, 10, 24));

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel46.setText("50");
        jLabel46.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, 24));

        jLabel47.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel47.setText("21");
        jLabel47.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, 24));

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel48.setText("-");
        jLabel48.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 560, 10, 24));

        jLabel49.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel49.setText("70");
        jLabel49.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, -1, 24));

        jLabel50.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel50.setText("51");
        jLabel50.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, -1, 24));

        jLabel51.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel51.setText("100+");
        jLabel51.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, 24));

        jLabel52.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel52.setText("Additional Charges");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 210, 30));

        jLabel53.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel53.setText("(per kWh)");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 60, 20));

        jLabel54.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel54.setText("Adt'l Charge");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 100, 20));

        txtGSAdd4.setBackground(new java.awt.Color(235, 235, 235));
        txtGSAdd4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtGSAdd4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGSAdd4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtGSAdd4.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtGSAdd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 80, -1));

        txtGSAdd1.setBackground(new java.awt.Color(235, 235, 235));
        txtGSAdd1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtGSAdd1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGSAdd1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtGSAdd1.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtGSAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 80, -1));

        txtGSAdd2.setBackground(new java.awt.Color(235, 235, 235));
        txtGSAdd2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtGSAdd2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGSAdd2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtGSAdd2.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtGSAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 80, -1));

        txtGSAdd3.setBackground(new java.awt.Color(235, 235, 235));
        txtGSAdd3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtGSAdd3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGSAdd3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtGSAdd3.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtGSAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 80, -1));

        jLabel55.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel55.setText("(kWh)");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 40, 20));

        jLabel56.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel56.setText("Consumption");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 110, 20));

        jLabel57.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel57.setText("-");
        jLabel57.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 10, 24));

        jLabel58.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel58.setText("200");
        jLabel58.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, 24));

        jLabel59.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel59.setText("0");
        jLabel59.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, 24));

        jLabel60.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel60.setText("-");
        jLabel60.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 10, 24));

        jLabel61.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel61.setText("300");
        jLabel61.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, 24));

        jLabel62.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel62.setText("201");
        jLabel62.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, 24));

        jLabel63.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel63.setText("-");
        jLabel63.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 10, 24));

        jLabel64.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel64.setText("400");
        jLabel64.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, 24));

        jLabel65.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel65.setText("301");
        jLabel65.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, 24));

        jLabel66.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel66.setText("400+");
        jLabel66.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, 24));

        jLabel67.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel67.setText("Discounts");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 210, 30));

        txtRService.setBackground(new java.awt.Color(235, 235, 235));
        txtRService.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRService.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRService.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtRService.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtRService, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 80, -1));

        txtRDisc4.setBackground(new java.awt.Color(235, 235, 235));
        txtRDisc4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRDisc4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRDisc4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtRDisc4.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtRDisc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 80, -1));

        jLabel68.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel68.setText("Service Charges");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, 210, 30));

        jLabel69.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel69.setText(" (per kW)");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 270, 60, 20));

        jLabel70.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel70.setText("Adt'l Charge");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 250, 100, 20));

        txtGPAdd1.setBackground(new java.awt.Color(235, 235, 235));
        txtGPAdd1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtGPAdd1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGPAdd1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtGPAdd1.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtGPAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 300, 120, -1));

        txtGPAdd2.setBackground(new java.awt.Color(235, 235, 235));
        txtGPAdd2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtGPAdd2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGPAdd2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtGPAdd2.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtGPAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 330, 120, -1));

        txtGPAdd3.setBackground(new java.awt.Color(235, 235, 235));
        txtGPAdd3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtGPAdd3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGPAdd3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtGPAdd3.setSelectionColor(new java.awt.Color(242, 100, 25));
        jPanel1.add(txtGPAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 360, 120, -1));

        jLabel71.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel71.setText("  (kW)");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 40, 20));

        jLabel72.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jLabel72.setText("Consumption");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 110, 20));

        jLabel73.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel73.setText("-");
        jLabel73.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, 10, 24));

        jLabel74.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel74.setText("200");
        jLabel74.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 300, -1, 24));

        jLabel75.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel75.setText("0");
        jLabel75.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, -1, 24));

        jLabel76.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel76.setText("-");
        jLabel76.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, 10, 24));

        jLabel77.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel77.setText("300");
        jLabel77.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 330, -1, 24));

        jLabel78.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel78.setText("201");
        jLabel78.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 330, -1, 24));

        jLabel82.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel82.setText("700+");
        jLabel82.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, -1, 24));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setText("Base Rate:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try{
            float[] newRates = {Float.parseFloat(txtBaseResidential.getText()),
                Float.parseFloat(txtRAdd1.getText()),
                Float.parseFloat(txtRAdd2.getText()),
                Float.parseFloat(txtRAdd3.getText()),
                Float.parseFloat(txtRAdd4.getText()),
                Float.parseFloat(txtRDisc1.getText()),
                Float.parseFloat(txtRDisc2.getText()),
                Float.parseFloat(txtRDisc3.getText()),
                Float.parseFloat(txtRDisc4.getText()),
                Float.parseFloat(txtRService.getText()),
                Float.parseFloat(txtBaseGS.getText()),
                Float.parseFloat(txtGSAdd1.getText()),
                Float.parseFloat(txtGSAdd2.getText()),
                Float.parseFloat(txtGSAdd3.getText()),
                Float.parseFloat(txtGSAdd4.getText()),
                Float.parseFloat(txtBaseGP.getText()),
                Float.parseFloat(txtGPAdd1.getText()),
                Float.parseFloat(txtGPAdd2.getText()),
                Float.parseFloat(txtGPAdd3.getText()),};
            
            if (input.equals("")){
                updateRates(cbxBillPeriod.getSelectedItem().toString(), newRates);
            } else{
                addNewRates(input, newRates);
                cbxBillPeriod.addItem(input);
                input = "";
            }
            
            cbxBillPeriod.setEnabled(true);
            btnNew.setEnabled(true);
            btnLogOut.setEnabled(true);
            
        } catch (NumberFormatException exc){
            showMessageDialog(null, "Check for fields that are empty or is or "
                    + "less than zero.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        mainmen.clearStoredInfo();
        mainmen.loggedIn = false;
        new mainmen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void cbxBillPeriodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxBillPeriodItemStateChanged
        
    }//GEN-LAST:event_cbxBillPeriodItemStateChanged

    private void cbxBillPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBillPeriodActionPerformed
        float[] rates = getRates(cbxBillPeriod.getSelectedItem().toString());
        txtBaseResidential.setText(String.valueOf(rates[0]));
        txtRAdd1.setText(String.valueOf(rates[1]));
        txtRAdd2.setText(String.valueOf(rates[2]));
        txtRAdd3.setText(String.valueOf(rates[3]));
        txtRAdd4.setText(String.valueOf(rates[4]));
        txtRDisc1.setText(String.valueOf(rates[5]));
        txtRDisc2.setText(String.valueOf(rates[6]));
        txtRDisc3.setText(String.valueOf(rates[7]));
        txtRDisc4.setText(String.valueOf(rates[8]));
        txtRService.setText(String.valueOf(rates[9]));
        txtBaseGS.setText(String.valueOf(rates[10]));
        txtGSAdd1.setText(String.valueOf(rates[11]));
        txtGSAdd2.setText(String.valueOf(rates[12]));
        txtGSAdd3.setText(String.valueOf(rates[13]));
        txtGSAdd4.setText(String.valueOf(rates[14]));
        txtBaseGP.setText(String.valueOf(rates[15]));
        txtGPAdd1.setText(String.valueOf(rates[16]));
        txtGPAdd2.setText(String.valueOf(rates[17]));
        txtGPAdd3.setText(String.valueOf(rates[18]));
    }//GEN-LAST:event_cbxBillPeriodActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        input = showInputDialog("Enter the billing period (MM-YYYY):");
        if (input.length() == 7 && input.indexOf("-") == 2){
            cbxBillPeriod.setEnabled(false);
            btnNew.setEnabled(false);
            btnLogOut.setEnabled(false);
            
        txtBaseResidential.setText("");
        txtRAdd1.setText("");
        txtRAdd2.setText("");
        txtRAdd3.setText("");
        txtRAdd4.setText("");
        txtRDisc1.setText("");
        txtRDisc2.setText("");
        txtRDisc3.setText("");
        txtRDisc4.setText("");
        txtRService.setText("");
        txtBaseGS.setText("");
        txtGSAdd1.setText("");
        txtGSAdd2.setText("");
        txtGSAdd3.setText("");
        txtGSAdd4.setText("");
        txtBaseGP.setText("");
        txtGPAdd1.setText("");
        txtGPAdd2.setText("");
        txtGPAdd3.setText("");
        } else{
            showMessageDialog(null, "Please check the format.");
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loadMonths(cbxBillPeriod);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new company().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbxBillPeriod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txtBaseGP;
    private javax.swing.JTextField txtBaseGS;
    private javax.swing.JTextField txtBaseResidential;
    private javax.swing.JTextField txtGPAdd1;
    private javax.swing.JTextField txtGPAdd2;
    private javax.swing.JTextField txtGPAdd3;
    private javax.swing.JTextField txtGSAdd1;
    private javax.swing.JTextField txtGSAdd2;
    private javax.swing.JTextField txtGSAdd3;
    private javax.swing.JTextField txtGSAdd4;
    private javax.swing.JTextField txtRAdd1;
    private javax.swing.JTextField txtRAdd2;
    private javax.swing.JTextField txtRAdd3;
    private javax.swing.JTextField txtRAdd4;
    private javax.swing.JTextField txtRDisc1;
    private javax.swing.JTextField txtRDisc2;
    private javax.swing.JTextField txtRDisc3;
    private javax.swing.JTextField txtRDisc4;
    private javax.swing.JTextField txtRService;
    // End of variables declaration//GEN-END:variables
}
