/**
 *
 * @author mangostynn
 */
package forms;
import javax.swing.JOptionPane;
import java.awt.*;

public class mainmen extends javax.swing.JFrame {
    // PUBLIC VARIABLES
    public static boolean loggedIn = false;
    public static String uid, username, password, firstName, lastName,
        address, email, serviceRate;
        GraphicsEnvironment ge = 
        GraphicsEnvironment.getLocalGraphicsEnvironment();
        Font RobotoText, RobotoTitle;   
        
    /**
     * Creates new form main
     */
    public mainmen() {
        try {
            this.setContentPane(new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/splash-bg.jpg"))));
            initComponents();
            RobotoText = Font.createFont(Font.TRUETYPE_FONT, getClass().getResource("/Roboto/Roboto-Regular.ttf").openStream());
            ge.registerFont(RobotoText);
            RobotoTitle = Font.createFont(Font.TRUETYPE_FONT, getClass().getResource("/Roboto/Roboto-Bold.ttf").openStream());
            ge.registerFont(RobotoTitle);
        } catch (Exception e ) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblCompanyName = new javax.swing.JLabel();
        pnlMainButtons = new javax.swing.JPanel();
        pnlPreLog = new javax.swing.JPanel();
        btnSignUp = new javax.swing.JButton();
        btnLogIn = new javax.swing.JButton();
        btnFAQPre = new javax.swing.JButton();
        pnlPostLog = new javax.swing.JPanel();
        btnPay = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        btnFAQPost = new javax.swing.JButton();
        pnlBody = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        setTitle("Home");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pnlHeader.setBackground(new java.awt.Color(242, 100, 25));

        lblCompanyName.setBackground(new java.awt.Color(255, 255, 255));
        lblCompanyName.setFont(new Font("RobotoTitle", Font.BOLD, 36));
        lblCompanyName.setForeground(new java.awt.Color(255, 255, 255));
        lblCompanyName.setText("HELIOS SYSTEM INC.");

        pnlMainButtons.setBackground(new java.awt.Color(255, 157, 84));
        pnlMainButtons.setLayout(new java.awt.CardLayout());

        pnlPreLog.setBackground(new java.awt.Color(242, 100, 25));
        pnlPreLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSignUp.setBackground(new java.awt.Color(242, 100, 25));
        btnSignUp.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        pnlPreLog.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 195, 36));

        btnLogIn.setBackground(new java.awt.Color(242, 100, 25));
        btnLogIn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        pnlPreLog.add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 195, 36));

        btnFAQPre.setBackground(new java.awt.Color(60, 63, 66));
        btnFAQPre.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnFAQPre.setForeground(new java.awt.Color(255, 255, 255));
        btnFAQPre.setText("?");
        btnFAQPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAQPreActionPerformed(evt);
            }
        });
        pnlPreLog.add(btnFAQPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 36));

        pnlMainButtons.add(pnlPreLog, "card2");

        pnlPostLog.setBackground(new java.awt.Color(242, 100, 25));
        pnlPostLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPay.setBackground(new java.awt.Color(242, 100, 25));
        btnPay.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Pay Now");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        pnlPostLog.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 195, 36));

        btnSignOut.setBackground(new java.awt.Color(242, 100, 25));
        btnSignOut.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnSignOut.setForeground(new java.awt.Color(255, 255, 255));
        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        pnlPostLog.add(btnSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 195, 36));

        btnFAQPost.setBackground(new java.awt.Color(60, 63, 66));
        btnFAQPost.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnFAQPost.setForeground(new java.awt.Color(255, 255, 255));
        btnFAQPost.setText("?");
        btnFAQPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAQPostActionPerformed(evt);
            }
        });
        pnlPostLog.add(btnFAQPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 36));

        pnlMainButtons.add(pnlPostLog, "card3");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblCompanyName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMainButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addComponent(pnlMainButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addComponent(lblCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Open Sans SemiBold", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pay your bills online as easy as 123!");
        pnlBody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 1280, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Open Sans SemiBold", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("1");

        jLabel4.setFont(new java.awt.Font("Open Sans SemiBold", 1, 48)); // NOI18N
        jLabel4.setText("2");

        jLabel5.setFont(new java.awt.Font("Open Sans SemiBold", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("3");

        jLabel9.setFont(new java.awt.Font("Open Sans SemiBold", 1, 48)); // NOI18N
        jLabel9.setText(">");

        jLabel10.setFont(new java.awt.Font("Open Sans SemiBold", 1, 48)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(">");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(jLabel9)
                .addGap(138, 138, 138)
                .addComponent(jLabel4)
                .addGap(138, 138, 138)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(jLabel5)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34))
        );

        jLabel6.setFont(new java.awt.Font("Open Sans SemiBold", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sign Up");

        jLabel7.setFont(new java.awt.Font("Open Sans SemiBold", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Log In");

        jLabel8.setFont(new java.awt.Font("Open Sans SemiBold", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pay");

        jLabel11.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Create your own account using your ");

        jLabel12.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Helios Customer ID.");

        jLabel13.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("If you have already created an account,");

        jLabel14.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Log in using your registered account.");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("View your bill information and");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Pay your bill with our selection of");

        jLabel17.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("payment methods.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(251, 251, 251))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pnlBody.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 1259, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        new signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnFAQPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAQPreActionPerformed
        new faqs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFAQPreActionPerformed

    private void btnFAQPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAQPostActionPerformed
        new faqs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFAQPostActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        new payment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        Object[] options = {"OK", "Cancel"};
        
        int answer = JOptionPane.showOptionDialog(null, "Click OK to continue.",
             "You are logging out.", JOptionPane.DEFAULT_OPTION,
             JOptionPane.WARNING_MESSAGE,null, options, options[0]);
        
        if (answer == 0){
            clearStoredInfo();
            loggedIn = false;
            pnlMainButtons.removeAll();
            pnlMainButtons.add(pnlPreLog);
            pnlMainButtons.repaint();
            pnlMainButtons.revalidate();
        }
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       if (loggedIn == true){
            pnlMainButtons.removeAll();
            pnlMainButtons.add(pnlPostLog);
            pnlMainButtons.repaint();
            pnlMainButtons.revalidate();
        } else{
            pnlMainButtons.removeAll();
            pnlMainButtons.add(pnlPreLog);
            pnlMainButtons.repaint();
            pnlMainButtons.revalidate();
       }
    }//GEN-LAST:event_formComponentShown
    
    public static void clearStoredInfo(){
        uid = "";
        username = "";
        password = "";
        firstName = "";
        lastName = "";
        address = "";
        email = "";
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainmen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFAQPost;
    private javax.swing.JButton btnFAQPre;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMainButtons;
    private javax.swing.JPanel pnlPostLog;
    private javax.swing.JPanel pnlPreLog;
    // End of variables declaration//GEN-END:variables
}
